# Install kube-prometheus-stack 
helm install monitor prometheus-community/kube-prometheus-stack
helm install monitor prometheus-community/kube-prometheus-stack -n kube-prom --create-namespace

kubectl port-forward svc/monitor-kube-prometheus-st-prometheus 9090:9090
kubectl port-forward svc/monitor-grafana 30000:80

kubectl get secret monitor-grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: salary-model-servicemonitor
  # namespace: monitoring
  labels:
    release: monitor      # MUST match your Helm release name
    app: salary-model      
spec:
  selector:
    matchLabels:          # match service with metadata.labels.app = house-price-serving
      app: salary-model     # MUST match labels in your Service
  namespaceSelector:
    matchNames:
      - default             # your service is in default namespace
  endpoints:
    - port: http            # MUST match service.port.name
      path: /metrics
      interval: 10s
      scrapeTimeout: 5s
